apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - env.yaml
  - monitoring-prefix-ingress.yaml
  - monitoring-rewrite-ingress.yaml

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus/prometheus.yml
      - prometheus/recording_rules.yml
  - name: grafana-datasources
    files:
      - provisioning/datasources/prometheus.yaml
  - name: grafana-dashboards
    files:
      - provisioning/dashboards/variables.yaml

generatorOptions:
  disableNameSuffixHash: true
