apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-prefix-ingress
  namespace: monitoring
  # No rewrite here—Grafana & Prometheus handle sub-paths themselves
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          # Grafana UI under /grafana
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000

          # Prometheus UI under /prometheus
          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
