apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-rewrite-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: ca-cluster-issuer
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - localhost
      secretName: monitoring-rewrite-tls

  rules:
    - host: localhost
      http:
        paths:
          - path: /rabbit(?:/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: rabbitmq-cluster
                port:
                  number: 15672

          - path: /nodered(?:/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: nodered
                port:
                  number: 1880
